services:
#   database:
#     container_name: database
#     hostname: database
#     image: postgres:16.1
#     env_file: .env
#     volumes: 
#       - ./database:/var/lib/postgresql/data
#     networks:
#       - transcendence
#     restart: unless-stopped
#     ports:
#       - 5432:5432

#   django:
#     container_name: django
#     hostname: django
#     env_file: .env
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend:/app
#     networks:
#       - transcendence
#     ports:
#       - 8000:8000
#     restart: unless-stopped
    
#     depends_on:
#       - database

  frontend:
    container_name: frontend
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    networks:
      - transcendence
    ports:
     - 8080:5173
    restart: unless-stopped
  
  backendsimulation:
    container_name: backendsimulation
    build:
      context: ./backendsimulation
      dockerfile: Dockerfile
    volumes:
      - ./backendsimulation:/app
    networks:
      - transcendence
    expose:
      - "8000"
    ports:
    - "8000:8000"
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge

    