# Generated by Django 5.0.6 on 2024-08-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PongGroup',
        ),
    ]
