# Generated by Django 5.0.6 on 2024-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pong', '0002_delete_ponggroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
