# Generated by Django 5.0.6 on 2024-09-11 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, unique=True)),
                ('users_online', models.ManyToManyField(blank=True, related_name='online_in_shooter_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
